/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments, } from "@stencil/router";
export namespace Components {
    interface AboutPage {
    }
    interface AppHome {
    }
    interface AppNav {
        /**
          * Router location
         */
        "location": LocationSegments;
    }
    interface AppRoot {
    }
    interface WorkedWith {
    }
}
declare global {
    interface HTMLAboutPageElement extends Components.AboutPage, HTMLStencilElement {
    }
    var HTMLAboutPageElement: {
        prototype: HTMLAboutPageElement;
        new (): HTMLAboutPageElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLWorkedWithElement extends Components.WorkedWith, HTMLStencilElement {
    }
    var HTMLWorkedWithElement: {
        prototype: HTMLWorkedWithElement;
        new (): HTMLWorkedWithElement;
    };
    interface HTMLElementTagNameMap {
        "about-page": HTMLAboutPageElement;
        "app-home": HTMLAppHomeElement;
        "app-nav": HTMLAppNavElement;
        "app-root": HTMLAppRootElement;
        "worked-with": HTMLWorkedWithElement;
    }
}
declare namespace LocalJSX {
    interface AboutPage {
    }
    interface AppHome {
    }
    interface AppNav {
        /**
          * Router location
         */
        "location"?: LocationSegments;
    }
    interface AppRoot {
    }
    interface WorkedWith {
    }
    interface IntrinsicElements {
        "about-page": AboutPage;
        "app-home": AppHome;
        "app-nav": AppNav;
        "app-root": AppRoot;
        "worked-with": WorkedWith;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "about-page": LocalJSX.AboutPage & JSXBase.HTMLAttributes<HTMLAboutPageElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "worked-with": LocalJSX.WorkedWith & JSXBase.HTMLAttributes<HTMLWorkedWithElement>;
        }
    }
}
